repos:
  - repo: https://github.com/python-poetry/poetry
    rev: "1.2.0b1" # add version here
    hooks:
      - id: poetry-check
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]
      - id: poetry-export
        args: ["--dev", "-f", "requirements.txt", "-o", "requirements-dev.txt"]
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3.10