repos:
  - repo: https://github.com/python-poetry/poetry
    rev: "1.2.0b1" # add version here
    hooks:
      - id: poetry-check
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3.10
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          - "-rn"
          - "-sn"