version: 3
services:
  smtp:
    image: docker.io/rnwood/smtp4dev:latest
    ports:
      - '5000:80' # WEB
      - '2500:25' # SMTP
      - '1430:143' # IMAP
    volumes:
      - smpt-data:/smtp4dev
volumes:
  smpt-data: