# Generated by Django 4.1.1 on 2022-09-21 02:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_disciplinas"),
    ]

    operations = [
        migrations.AddField(
            model_name="disciplinas",
            name="monitores",
            field=models.ManyToManyField(
                blank=True, related_name="monitoria", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="disciplinas",
            name="professores",
            field=models.ManyToManyField(
                blank=True, related_name="disciplinas", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
