# Generated by Django 4.1.2 on 2022-10-17 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_disciplinas_monitores_disciplinas_professores"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("presencial", "Presencial"), ("virtual", "Virtual")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmado", "Confirmado"),
                            ("aguardando", "Aguardando Confirmação"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="aguardando",
                        max_length=10,
                    ),
                ),
                ("data", models.DateTimeField()),
                ("assunto", models.TextField()),
                ("descricao", models.TextField()),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.disciplinas",
                    ),
                ),
                (
                    "solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
