# Generated by Django 4.1.3 on 2024-01-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_agendamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="link_zoom",
            field=models.TextField(null=True),
        ),
    ]
