# Generated by Django 4.1.2 on 2023-06-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_agendamento"),
        ("core", "0004_arquivo"),
    ]

    operations = []
