# Generated by Django 4.1.3 on 2022-11-30 19:21

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_agendamento"),
    ]

    operations = [
        migrations.CreateModel(
            name="Arquivo",
            fields=[
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("alterado_em", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("arquivo", models.FileField(upload_to="")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
