# Generated by Django 4.1.3 on 2024-01-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_agendamento_link_zoom"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="agendamento",
            constraint=models.UniqueConstraint(
                fields=("data", "disciplina"), name="agendamento_unico"
            ),
        ),
    ]
