# Generated by Django 4.1.3 on 2024-01-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_agendamento_agendamento_unico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendamento",
            name="link_zoom",
            field=models.TextField(blank=True, null=True),
        ),
    ]
