# Generated by Django 4.2.15 on 2024-08-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_agendamento_link_zoom"),
    ]

    operations = [
        migrations.CreateModel(
            name="Monitoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
