# Generated by Django 4.2.16 on 2024-09-26 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0007_alter_agendamento_link_zoom"),
    ]

    operations = [
        migrations.CreateModel(
            name="Monitoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0", "Segunda-feira"),
                            ("1", "Terça-feira"),
                            ("2", "Quarta-feira"),
                            ("3", "Quinta-feira"),
                            ("4", "Sexta-feira"),
                            ("5", "Sábado"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("hora_inicio", models.TimeField(blank=True, null=True)),
                ("hora_fim", models.TimeField(blank=True, null=True)),
                ("local", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "disciplina",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="DisciplinaMonitorias",
                        to="core.disciplinas",
                    ),
                ),
                (
                    "monitor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Monitorias_como_monitor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitorias_como_professor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="monitoria",
            constraint=models.UniqueConstraint(
                fields=("monitor", "disciplina", "dia_semana", "hora_inicio"),
                name="horario_unico",
            ),
        ),
    ]
