# Generated by Django 4.2.15 on 2024-09-04 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0008_monitoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoria",
            name="dia_semana",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "Segunda-feira"),
                    ("1", "Terça-feira"),
                    ("2", "Quarta-feira"),
                    ("3", "Quinta-feira"),
                    ("4", "Sexta-feira"),
                    ("5", "Sábado"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="monitoria",
            name="disciplina",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="DisciplinaMonitorias",
                to="core.disciplinas",
            ),
        ),
        migrations.AddField(
            model_name="monitoria",
            name="hora_fim",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="monitoria",
            name="hora_inicio",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="monitoria",
            name="local",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="monitoria",
            name="monitor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Monitorias_como_monitor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="monitoria",
            name="professor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monitorias_como_professor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="monitoria",
            constraint=models.UniqueConstraint(
                fields=("monitor", "disciplina", "dia_semana", "hora_inicio"),
                name="horario_unico",
            ),
        ),
    ]
