# Generated by Django 4.0.4 on 2022-06-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailactivationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_email_active',
            field=models.BooleanField(default=False),
        ),
    ]
