# Generated by Django 4.0.6 on 2022-07-15 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="entrada",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Campo não está formatado corretamente.",
                        regex="\\d{4}\\.[12]",
                    )
                ],
            ),
        ),
    ]
