# Generated by Django 4.1.2 on 2022-11-14 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_arquivo"),
        ("accounts", "0005_perfil_entrada"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="foto",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.arquivo",
            ),
        ),
    ]
