# Generated by Django 4.1.3 on 2023-08-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_perfil_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="imagens"),
        ),
    ]
