# Generated by Django 4.2.11 on 2024-04-23 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_remove_emailactivationtoken_activated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailactivationtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 23, 14, 14, 54, 677188, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
