# Generated by Django 4.2.11 on 2024-04-24 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_emailactivationtoken_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailactivationtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 24, 23, 37, 36, 943313, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
