# Generated by Django 4.2.11 on 2024-04-25 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_emailactivationtoken_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailactivationtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 25, 18, 30, 43, 741912, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
