# Generated by Django 4.2.11 on 2024-04-27 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_emailactivationtoken_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailactivationtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 27, 17, 55, 59, 960799, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
