# Generated by Django 4.2.11 on 2024-04-28 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_emailactivationtoken_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailactivationtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 28, 2, 12, 25, 797890, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
