# Generated by Django 4.2.11 on 2024-05-08 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_alter_emailactivationtoken_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailactivationtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 8, 21, 24, 1, 831247, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
