
# Generated by Django 4.2.11 on 2024-05-23 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_alter_emailactivationtoken_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailactivationtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 23, 17, 5, 37, 92790, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
# Django 4.2.15 on 2024-08-19 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_alter_emailactivationtoken_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailactivationtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 8, 19, 13, 12, 33, 967068, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]

