# Generated by Django 4.2.11 on 2024-05-23 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_alter_emailactivationtoken_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailactivationtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 23, 17, 53, 1, 673150, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
