# Generated by Django 4.2.16 on 2024-09-26 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_alter_emailactivationtoken_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailactivationtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 26, 23, 17, 2, 870692, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
