# Generated by Django 4.1.3 on 2025-01-30 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_alter_emailactivationtoken_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailactivationtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 30, 12, 21, 31, 596205, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
