# Generated by Django 4.2.16 on 2025-05-19 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_alter_emailactivationtoken_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailactivationtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 19, 19, 43, 14, 288083, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
