# Generated by Django 4.2.16 on 2025-05-20 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_alter_emailactivationtoken_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailactivationtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 20, 12, 19, 2, 588109, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
