# Generated by Django 5.2.1 on 2025-05-26 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_emailactivationtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailactivationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 26, 20, 10, 51, 499210, tzinfo=datetime.timezone.utc)),
        ),
    ]
