# Generated by Django 5.2.1 on 2025-05-26 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_emailactivationtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailactivationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 26, 22, 0, 45, 858917, tzinfo=datetime.timezone.utc)),
        ),
    ]
