# Generated by Django 4.2.16 on 2025-10-19 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_alter_emailactivationtoken_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailactivationtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 10, 19, 22, 54, 9, 545155, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
