# Generated by Django 4.2.25 on 2025-10-20 00:20

from django.db import migrations, models
import accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_alter_emailactivationtoken_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailactivationtoken",
            name="expires_at",
            field=models.DateTimeField(default=accounts.models.get_token_expiry),
        ),
    ]
