# Generated by Django 4.2.25 on 2025-10-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0028_alter_emailactivationtoken_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="siape",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
