# Generated by Django 4.2.16 on 2025-10-19 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0029_alter_emailactivationtoken_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailactivationtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 10, 19, 23, 28, 27, 722259, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
