# Generated by Django 4.2.25 on 2025-10-20 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0031_alter_emailactivationtoken_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailactivationtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 10, 20, 0, 19, 15, 143383, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
