# Generated by Django 4.0.4 on 2022-07-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Duvida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField(max_length=550)),
                ("privacidade_autor", models.BooleanField(default=True)),
                ("arquivo", models.FileField(upload_to="")),
            ],
        ),
    ]
