# Generated by Django 4.1 on 2022-08-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum_amo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="duvida",
            name="data",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
