# Generated by Django 4.0.4 on 2022-07-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum_amo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="duvida",
            name="imagem",
            field=models.ImageField(default=None, upload_to="amo-backend/imagens"),
        ),
        migrations.AlterField(
            model_name="duvida",
            name="arquivo",
            field=models.FileField(upload_to="amo-backend/arquivos"),
        ),
    ]
