# Generated by Django 4.0.6 on 2022-08-05 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum_amo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resposta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resposta", models.TextField(max_length=750)),
                ("data_criada", models.DateTimeField(auto_now=True)),
                (
                    "duvida_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forum_amo.duvida",
                    ),
                ),
            ],
        ),
    ]
