# Generated by Django 4.1 on 2022-08-28 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_disciplinas"),
        ("forum_amo", "0002_duvida_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="duvida",
            name="disciplina",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.disciplinas",
            ),
            preserve_default=False,
        ),
    ]
