# Generated by Django 4.1 on 2022-08-28 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum_amo", "0003_duvida_disciplina"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resposta",
            old_name="data_criada",
            new_name="data",
        ),
    ]
