# Generated by Django 4.1 on 2022-08-31 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forum_amo", "0004_rename_data_criada_resposta_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="duvida",
            name="resposta_correta",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="forum_amo.resposta",
            ),
        ),
    ]
