# Generated by Django 4.0.6 on 2022-09-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum_amo", "0006_votoduvida"),
    ]

    operations = [
        migrations.AddField(
            model_name="duvida",
            name="votos",
            field=models.IntegerField(default=0),
        ),
    ]
