# Generated by Django 4.1.3 on 2023-07-03 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forum_amo", "0006_duvida_votos_votoduvida_votoduvida_voto_unico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="duvida",
            name="resposta_correta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="forum_amo.resposta",
            ),
        ),
    ]
