# Generated by Django 4.1.3 on 2023-06-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum_amo", "0006_duvida_votos_votoduvida_votoduvida_voto_unico"),
    ]

    operations = [
        migrations.AddField(
            model_name="duvida",
            name="imagem",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
