# Generated by Django 4.1.3 on 2023-08-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum_amo", "0007_alter_duvida_resposta_correta"),
    ]

    operations = [
        migrations.AddField(
            model_name="duvida",
            name="quantidade_comentarios",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
