# Generated by Django 4.0.6 on 2022-09-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum_amo", "0007_duvida_votos"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="votoduvida",
            constraint=models.UniqueConstraint(
                fields=("usuario", "duvida"), name="voto_unico"
            ),
        ),
    ]
