# Generated by Django 4.1.3 on 2023-06-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum_amo", "0007_duvida_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="resposta",
            name="imagem",
            field=models.ImageField(blank=True, upload_to="imagens/"),
        ),
        migrations.AlterField(
            model_name="duvida",
            name="imagem",
            field=models.ImageField(blank=True, upload_to="imagens/"),
        ),
    ]
