# Generated by Django 4.2.11 on 2024-05-23 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forum_amo", "0008_duvida_quantidade_comentarios"),
    ]

    operations = [
        migrations.CreateModel(
            name="Denuncia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("Ameaças", "Ameaças"),
                            ("Bullying", "Bullying"),
                            ("SPAM", "SPAM"),
                            ("Bullying", "Bullying"),
                            ("SPAM", "SPAM"),
                        ],
                        max_length=50,
                    ),
                ),
                ("descricao", models.TextField(max_length=200)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "duvida",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forum_amo.duvida",
                    ),
                ),
                (
                    "resposta",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forum_amo.resposta",
                    ),
                ),
            ],
        ),
    ]
