# Generated by Django 4.1.3 on 2025-01-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum_amo", "0009_denuncia"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="duvida",
            name="resposta_correta",
        ),
        migrations.AddField(
            model_name="duvida",
            name="resposta_correta",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="+", to="forum_amo.resposta"
            ),
        ),
    ]
